### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by VolkMilit** [TES3MP/TES3MP#171] opened 2017-02-25 13:38 UTC
Item are duplicated when you take an item from the container, and then put it back. And seams like duplicate, when you try to put item from inventory to container.

**Comment by davidcernat** [comment] 2017-02-25 15:02
Very strange, and this certainly did not happen a few days ago.

For some reason, when a player sends an ID_CONTAINER packet, the server then sends it back to them.

I'll look into why this happens.

When Koncord mentioned you had noticed a bug, I thought it was the one where you duplicate items by clicking on them at the same time as another player, but this is far worse.

Edit: The problem was caused by commit 7065569f9b6b96f1319dfea13fe3fdaeeb295222 from 2 days ago.

More specifically, by the fact that the packet's guid was previously assigned here:

https://github.com/TES3MP/openmw-tes3mp/commit/7065569f9b6b96f1319dfea13fe3fdaeeb295222#diff-240f684f759a17c013807cc4e9c2b1afL481

But was no longer assigned to the baseEvent here:

https://github.com/TES3MP/openmw-tes3mp/commit/7065569f9b6b96f1319dfea13fe3fdaeeb295222#diff-240f684f759a17c013807cc4e9c2b1afR476

Hence, the server had a baseEvent with a guid of -1, and did not know who to avoid sending world packets to twice.

That had no effect on placing or removing items in the world because of their unique reference numbers, but affected containers.

**Comment by davidcernat** [comment] 2017-02-25 15:52
Fixed in 7917badedf548996754f53d0760b7da09f95bc23 and added to the 0.5.1 release for Windows.

**Closed as completed by davidcernat** 2017-02-25 15:52 UTC
Labels: Bug, Confirmed
