### ISSUE TITLE
NPCs Randomly Moving Positions and Dying

### ISSUE THREAD

**Issue by Jaboo36** [TES3MP/TES3MP#537] opened 2019-10-10 05:58 UTC
I created a server for my friends and I to play on and we noticed that npcs that were supposed to stay in one spot weren't. Multiple npcs positions were shifting around randomly. The silt strider rider in Balmora somehow fell off of his platform and died, and a boat captain fell off the dock he was standing on and was just floating in the water. Also a lady in Seyda Neen was just randomly dead when  we first went into the town. Is there a fix for this and is this a known issue?

**Comment by uramer** [comment] 2020-08-14 10:24
This is a known issue both with vanilla Morrowind and OpenMW. It is caused by idle animations slowly moving NPCs.
I suggest we close the issue @davidcernat

**Closed as completed** 2020-08-14 10:30 UTC
