### ISSUE TITLE
Sometimes unable to see other players

### ISSUE THREAD

**Issue by testman42** [TES3MP/TES3MP#32] opened 2016-08-04 12:01 UTC
In rare cases, after joining the server, player can see other players' chat but can not see their characters anywhere in the world.
Probably an issue with transfer of other players' data packets.

**Comment by Koncord** [comment] 2016-08-04 14:16
> Probably an issue with transfer of other players' data packets.

No, packets have high priority and reliable delivery. it means packets cannot be lost (like TCP behavior).

**Comment by Koncord** [comment] 2016-08-04 14:19
I think that the problem is related to this #11 and [this](https://github.com/TES3MP/openmw-tes3mp/blob/master/apps/openmw/mwmp/DedicatedPlayer.cpp#L78) code

**Comment by davidcernat** [comment] 2016-08-17 02:27
It doesn't seem related to issue #11 that much...

To recreate this bug, join a server with 2 clients, then leave with both and reconnect. After enough tries, at least one of them will not be able to see the other anymore.

**Comment by davidcernat** [comment] 2016-08-17 18:28
Now I'm having trouble recreating the issue... how strange. Maybe something we did last night alleviated it.

**Comment by davidcernat** [comment] 2016-08-18 21:10
Had a conversation with Koncord about this issue:

12:04 AM - David C.: 2) How do I make sure that this line returns true when a player rejoins?
12:04 AM - David C.: https://github.com/TES3MP/openmw-tes3mp/blob/master/apps/openmw-mp/Networking.cpp#L154
12:04 AM - David C.: Let me tell you what happens sometimes.
12:05 AM - David C.: I join the server with client 1, who is a High Elf.
12:05 AM - David C.: Then I join the server with client 2, who is a Khajiit.
12:05 AM - David C.: They see each other fine. No problem at all.
12:05 AM - David C.: I leave with the Khajiit and then rejoin.
12:05 AM - David C.: For some reason, the server now thinks the Khajiit is dead.
12:05 AM - David C.: As a result, the server will not accept any ID_GAME_CELL packets from the Khajiit.
12:06 AM - David C.: The Khajiit can see the High Elf just fine.
12:06 AM - David C.: However, the High Elf can never see the Khajiit again.
12:06 AM - David C.: If the Khajiit moves to another cell, the server again rejects his ID_GAME_CELL because it thinks he is dead.
12:06 AM - David C.: In fact, the server rejects even ID_GAME_UPDATE_POS from the Khajiit.
12:07 AM - Koncord: object is not updated state
12:07 AM - David C.: So now, from the High Elf's perspective and every other player who joins, the Khajiit is stuck in ToddTest
12:07 AM - David C.: Never moving again.
12:07 AM - Koncord: hmm/
12:07 AM - David C.: That is really what is going on with this issue:
12:07 AM - David C.: https://github.com/TES3MP/openmw-tes3mp/issues/32
12:07 AM - David C.: And it's a major problem.
12:07 AM - David C.: Because it's very unpredictable.
12:07 AM - David C.: It really is the most important thing to fix.

**Comment by davidcernat** [comment] 2016-08-19 00:13
Possibly fixed by e1955b440fe22f5763d9ca5b39998d1aa2f0b4e3. Requires testing.

**Closed as completed** 2016-08-24 16:24 UTC
Labels: Bug, Feedback needed
